"""add_checkout_entities_and_promocodes

Revision ID: 144e0955223f
Revises: 5fcb6c05b7c6
Create Date: 2026-09-17 10:15:10.383341

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "144e0955223f"
down_revision: Union[str, Sequence[str], None] = "5fcb6c05b7c6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "promocodes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("discount_percentage", sa.Integer(), nullable=True),
        sa.Column("discount_fixed", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_promocodes_code"), "promocodes", ["code"], unique=True)
    op.create_index(op.f("ix_promocodes_id"), "promocodes", ["id"], unique=False)
    op.create_table(
        "addresses",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("address_line", sa.String(length=255), nullable=False),
        sa.Column("floor", sa.String(length=50), nullable=True),
        sa.Column("apartment", sa.String(length=50), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_addresses_id"), "addresses", ["id"], unique=False)
    op.create_table(
        "payment_methods",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("card_name", sa.String(length=100), nullable=False),
        sa.Column("last_four_digits", sa.String(length=4), nullable=False),
        sa.Column("expiry_date", sa.String(length=5), nullable=False),
        sa.Column("provider_token", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_payment_methods_id"), "payment_methods", ["id"], unique=False
    )
    op.add_column(
        "orders", sa.Column("receiver_name", sa.String(length=255), nullable=True)
    )
    op.add_column(
        "orders", sa.Column("receiver_phone", sa.String(length=50), nullable=True)
    )
    delivery_type_enum = postgresql.ENUM("PICKUP", "DELIVERY", name="deliverytype")
    delivery_type_enum.create(op.get_bind(), checkfirst=True)
    op.add_column(
        "orders",
        sa.Column(
            "delivery_type",
            postgresql.ENUM("PICKUP", "DELIVERY", name="deliverytype", create_type=False),
            nullable=False,
        ),
    )
    op.add_column(
        "orders", sa.Column("delivery_address", sa.String(length=255), nullable=True)
    )
    op.add_column(
        "orders", sa.Column("delivery_floor", sa.String(length=50), nullable=True)
    )
    op.add_column(
        "orders", sa.Column("delivery_apartment", sa.String(length=50), nullable=True)
    )
    op.add_column("orders", sa.Column("promocode_id", sa.Integer(), nullable=True))
    op.add_column(
        "orders", sa.Column("promocode_str", sa.String(length=50), nullable=True)
    )
    op.add_column("orders", sa.Column("comment", sa.Text(), nullable=True))
    op.add_column(
        "orders",
        sa.Column("subtotal", sa.Numeric(precision=10, scale=2), nullable=False),
    )
    op.add_column(
        "orders",
        sa.Column("delivery_cost", sa.Numeric(precision=10, scale=2), nullable=False),
    )
    op.add_column(
        "orders",
        sa.Column("discount_amount", sa.Numeric(precision=10, scale=2), nullable=False),
    )
    op.alter_column(
        "orders",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.create_foreign_key(
        "fk_orders_promocode_id",
        "orders",
        "promocodes",
        ["promocode_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.alter_column("products", "is_active", existing_type=sa.BOOLEAN(), nullable=False)
    op.alter_column(
        "products",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "refresh_tokens", "revoked", existing_type=sa.BOOLEAN(), nullable=False
    )
    op.alter_column(
        "refresh_tokens",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "reviews",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column("users", "is_active", existing_type=sa.BOOLEAN(), nullable=False)
    op.alter_column("users", "is_admin", existing_type=sa.BOOLEAN(), nullable=False)
    op.alter_column(
        "users",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "users",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "users",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column("users", "is_admin", existing_type=sa.BOOLEAN(), nullable=True)
    op.alter_column("users", "is_active", existing_type=sa.BOOLEAN(), nullable=True)
    op.alter_column(
        "reviews",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "refresh_tokens",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "refresh_tokens", "revoked", existing_type=sa.BOOLEAN(), nullable=True
    )
    op.alter_column(
        "products",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column("products", "is_active", existing_type=sa.BOOLEAN(), nullable=True)
    op.drop_constraint("fk_orders_promocode_id", "orders", type_="foreignkey")
    op.alter_column(
        "orders",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.drop_column("orders", "discount_amount")
    op.drop_column("orders", "delivery_cost")
    op.drop_column("orders", "subtotal")
    op.drop_column("orders", "comment")
    op.drop_column("orders", "promocode_str")
    op.drop_column("orders", "promocode_id")
    op.drop_column("orders", "delivery_apartment")
    op.drop_column("orders", "delivery_floor")
    op.drop_column("orders", "delivery_address")
    op.drop_column("orders", "delivery_type")
    op.drop_column("orders", "receiver_phone")
    op.drop_column("orders", "receiver_name")
    op.drop_index(op.f("ix_payment_methods_id"), table_name="payment_methods")
    op.drop_table("payment_methods")
    op.drop_index(op.f("ix_addresses_id"), table_name="addresses")
    op.drop_table("addresses")
    op.drop_index(op.f("ix_promocodes_id"), table_name="promocodes")
    op.drop_index(op.f("ix_promocodes_code"), table_name="promocodes")
    op.drop_table("promocodes")
    delivery_type = sa.Enum("PICKUP", "DELIVERY", name="deliverytype")
    delivery_type.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###